# DAY-8


## Numpy

### 1.1 Basics of numpy 

In [1]:
import numpy as np

In [2]:
##1-D arrays
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [6]:
print(array.ndim) #checking dimention
print(array.shape) # for checking shape
print(array.size) # shows size of array or else no of element sin array
print(array.dtype) # shows dattype of array

1
(6,)
6
int32


In [10]:
# 2-D arrays
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(array2.ndim)
print(array2.shape)
print(array2.size)
print(array2.dtype)

2
(3, 3)
9
int32


In [12]:
# array using ARANGE
np.arange(0,10)#creating array from 0 to 9 ane dimention


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# array creating step
a = np.arange(0,11,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.zeros(5)#creates arrays of zero elements

array([0., 0., 0., 0., 0.])

In [17]:
b = np.zeros(shape=(4,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
# creating ones arrays
c = np.ones(shape=(4,5))
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
#creating arays using LINSPACE
d = np.linspace(0,5,10)#creates 1-D array b/w 0 and 5
                       # third argument -10 represents the no of elements in the array
                       # all elements ar eevenly spaced
d

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
#creating array using RANDOM
arrayr = np.random.rand(5)
arrayr

array([0.26389738, 0.33660371, 0.84734606, 0.56985224, 0.61073915])

In [26]:
array3 = np.random.rand(4,5)
array3

array([[0.49713761, 0.46502287, 0.77375855, 0.16754735, 0.6173237 ],
       [0.38070279, 0.28615312, 0.28240525, 0.19664866, 0.46641058],
       [0.71391979, 0.61551155, 0.37136941, 0.06420638, 0.44039291],
       [0.99345269, 0.67805933, 0.6906688 , 0.41539131, 0.15044912]])

In [29]:
# RANDOM RANDIT - for intigers values
d = np.random.randint(low=1,high=10,size=(4,4))
d

array([[7, 2, 6, 3],
       [6, 1, 1, 8],
       [2, 8, 1, 3],
       [3, 8, 5, 1]])

In [30]:
#random normally distributed
np.random.randn(5)

array([-1.04553212, -1.12134597,  1.03366574, -0.46908348, -0.73170726])

In [31]:
np.random.randn(5,5)

array([[-1.29907545e+00,  5.01905683e-01,  1.05662457e+00,
         1.34103486e+00,  4.19792830e-01],
       [-5.93464779e-01,  6.66193602e-02,  6.54836600e-01,
        -1.98653313e-01,  6.85844984e-01],
       [ 2.67854232e-01,  8.63171260e-01, -1.11155425e-01,
        -2.36738658e-01,  6.82270731e-02],
       [ 1.22487562e-01,  1.12917062e+00, -1.34009631e+00,
        -1.54385584e-01, -5.56793141e-01],
       [ 6.72863179e-01, -7.13032048e-01,  3.60323558e-05,
         2.08589523e-01,  5.64139849e-01]])

### 1.2 Array Operations

#### Reshape

In [33]:
array4 = np.arange(20)
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
#converting 1-D array to 2-D array using reshape
array4.reshape(5,4)
# We can reshape only by presentin same elements like
#in above there are 20 so we can reshape using 20 elements

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

#### MAX/MIN

In [38]:
randomrr = np.random.randint(2,100,10)
randomrr

array([70,  9, 10, 65, 95, 60, 68, 83, 32, 47])

In [39]:
#for minimum value
randomrr.min()

9

In [40]:
#for max value
randomrr.max()

95

In [42]:
#method to find index where min is present
randomrr.argmin()

1

In [43]:
#method to find index where max is present
randomrr.argmax()

4

#### mathematics

In [44]:
array_1 = np.arange(0,20)
array_2 = np.arange(100,120)

In [47]:
print(array_1+array_2)#addition
print('-'*120)
print(array_1-array_2)#subtraction
print('-'*120)
print(array_1*array_2)#multiplication
print('-'*120)
print(array_1/array_2)#division

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138]
------------------------------------------------------------------------------------------------------------------------
[-100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100]
------------------------------------------------------------------------------------------------------------------------
[   0  101  204  309  416  525  636  749  864  981 1100 1221 1344 1469
 1596 1725 1856 1989 2124 2261]
------------------------------------------------------------------------------------------------------------------------
[0.         0.00990099 0.01960784 0.02912621 0.03846154 0.04761905
 0.05660377 0.06542056 0.07407407 0.08256881 0.09090909 0.0990991
 0.10714286 0.11504425 0.12280702 0.13043478 0.13793103 0.14529915
 0.15254237 0.15966387]


In [48]:
array_1 +10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [49]:
array_2 *10

array([1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090, 1100,
       1110, 1120, 1130, 1140, 1150, 1160, 1170, 1180, 1190])

In [50]:
#sqyareroot
np.sqrt(array_1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [51]:
#logs
np.log(array_1)

C:\Users\vishrut\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

#### Statistics

In [52]:
array5 = np.random.rand(8)

In [54]:
array5.reshape(2,4)

array([[0.23333694, 0.21988552, 0.00456299, 0.11967802],
       [0.41640854, 0.28159195, 0.54130239, 0.75195753]])

In [55]:
array5.mean()

0.3210904861763549

In [56]:
np.mean(array5)

0.3210904861763549

In [58]:
np.mean(array5.reshape(2,4),axis=0)#finds means column wise

array([0.32487274, 0.25073874, 0.27293269, 0.43581778])

In [59]:
np.mean(array5.reshape(2,4),axis=1)#finds means row wise

array([0.14436587, 0.49781511])

In [60]:
np.std(array5)# for standard deviation

0.22457880855948326

In [61]:
np.std(array5.reshape(2,4),axis=0)#it gives SD column wise

array([0.0915358 , 0.03085322, 0.2683697 , 0.31613975])

In [62]:
np.std(array5.reshape(2,4),axis=1)#it gives SD row wise

array([0.09188771, 0.17310329])

In [64]:
array5.sum()#adds all the values

2.568723889410839

In [66]:
np.sum(array5.reshape(2,4),axis=0)

array([0.64974548, 0.50147747, 0.54586538, 0.87163556])

In [67]:
np.sum(array5.reshape(2,4),axis=1)

array([0.57746347, 1.99126042])

### 1.3 Array Indexing

#### 1-D array indexing

In [68]:
arr1 = np.arange(10,21)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [69]:
arr1[7] # finding value of index 7

17

In [71]:
arr1[1:6] #slicing

array([11, 12, 13, 14, 15])

#### 2-D aray

In [72]:
arr2 = np.array([[1,2,3,4],[44,55,66,77],[5,6,7,8]])
arr2

array([[ 1,  2,  3,  4],
       [44, 55, 66, 77],
       [ 5,  6,  7,  8]])

In [73]:
arr2.shape

(3, 4)

In [74]:
arr2[0,1]# extracting the element

2

In [76]:
'''SLICING[STARTROW:STOPROW:STEPROW,STARTCOL:STOPCOL:STEPCOL]'''
arr2[0:2,1:3]# slicing from rows elements and then from column elements

array([[ 2,  3],
       [55, 66]])

#### Conditional slicing

In [77]:
arr2 = np.arange(0,15)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [79]:
check = arr2 > 5
check

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [82]:
arr2[check]#whenever it is true we slice it for 'check' this condition

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
arr2[arr2>10]

array([11, 12, 13, 14])

## Pandas

### 1.1 Basics of Pandas

In [85]:
#it works with data frame

In [86]:
import pandas as pd

#### creation of series

In [108]:
#series is 1-D data

In [87]:
my_list = [10,20,30,40]

In [88]:
#series object have index labels
pd.Series(data=my_list)

0    10
1    20
2    30
3    40
dtype: int64

In [89]:
#customization of index
pd.Series(data=my_list,index=['a','b','c','d'])

a    10
b    20
c    30
d    40
dtype: int64

##### creating series using dictionaries

In [90]:
mydict = {'a':10,'b':20,'c':30,'d':40}
mydict

{'a': 10, 'b': 20, 'c': 30, 'd': 40}

In [91]:
pd.Series(mydict)

a    10
b    20
c    30
d    40
dtype: int64

#### Accessing series values

In [95]:
series1 = pd.Series([10,20,30,40,99],index=['Indore','Delhi','Mumbai','Pune','Vadodara'])
series1

Indore      10
Delhi       20
Mumbai      30
Pune        40
Vadodara    99
dtype: int64

In [96]:
series1['Indore']

10

### 1.2 Pandas - Dataframes

In [149]:
#they are more then 1-D data like the are 2-D data

In [97]:
#Creation of data frame
from numpy.random import randint

In [99]:
df = pd.DataFrame(randint(10,100,20).reshape(5,4),index=['A','B','C','D','E']
                 ,columns = ['GEN','DEL','NOI','FED'])
df

GEN  DEL  NOI  FED
A   75   30   94   59
B   34   25   13   73
C   76   32   67   66
D   52   77   39   54
E   29   40   34   61

In [101]:
df['GEN']#using label slicing to pull out a particular column

A    75
B    34
C    76
D    52
E    29
Name: GEN, dtype: int32

In [104]:
type(df['GEN'])

pandas.core.series.Series

In [106]:
#accessing more than one column
df[['GEN','DEL']]

GEN  DEL
A   75   30
B   34   25
C   76   32
D   52   77
E   29   40

In [110]:
type(df[['GEN','DEL']])

pandas.core.frame.DataFrame

In [112]:
df[['GEN','DEL','FED']]

GEN  DEL  FED
A   75   30   59
B   34   25   73
C   76   32   66
D   52   77   54
E   29   40   61

##### Adding new column to data

In [113]:
df

GEN  DEL  NOI  FED
A   75   30   94   59
B   34   25   13   73
C   76   32   67   66
D   52   77   39   54
E   29   40   34   61

In [114]:
df['SML'] = df['DEL']+df['GEN']
df

GEN  DEL  NOI  FED  SML
A   75   30   94   59  105
B   34   25   13   73   59
C   76   32   67   66  108
D   52   77   39   54  129
E   29   40   34   61   69

In [115]:
df['HYD'] = 75
df

GEN  DEL  NOI  FED  SML  HYD
A   75   30   94   59  105   75
B   34   25   13   73   59   75
C   76   32   67   66  108   75
D   52   77   39   54  129   75
E   29   40   34   61   69   75

In [116]:
df['BAN'] = [85,np.nan,63,25,43]#np.nan = null value
df

GEN  DEL  NOI  FED  SML  HYD   BAN
A   75   30   94   59  105   75  85.0
B   34   25   13   73   59   75   NaN
C   76   32   67   66  108   75  63.0
D   52   77   39   54  129   75  25.0
E   29   40   34   61   69   75  43.0

##### Removing columns

In [118]:
sf = df.drop('HYD',axis=1) # Axis = 1, means dropping the columns
sf

GEN  DEL  NOI  FED  SML   BAN
A   75   30   94   59  105  85.0
B   34   25   13   73   59   NaN
C   76   32   67   66  108  63.0
D   52   77   39   54  129  25.0
E   29   40   34   61   69  43.0

In [125]:
df# original dataframe doesnot change

GEN  DEL  NOI  FED  SML   BAN
A   75   30   94   59  105  85.0
B   34   25   13   73   59   NaN
C   76   32   67   66  108  63.0
D   52   77   39   54  129  25.0
E   29   40   34   61   69  43.0

In [127]:
df.drop('BAN',axis=1,inplace=True)#inplace=True, updates the value of the variable starting the dataframe
df

GEN  DEL  NOI  FED  SML
A   75   30   94   59  105
B   34   25   13   73   59
C   76   32   67   66  108
D   52   77   39   54  129
E   29   40   34   61   69

In [128]:
# to drop multiple columns
df.drop(['GEN','NOI'],axis=1,inplace=True)#to drop multiple columns use a list of columns
df

DEL  FED  SML
A   30   59  105
B   25   73   59
C   32   66  108
D   77   54  129
E   40   61   69

In [130]:
df.drop('E',axis=0)#  To drop the row NOTE inplace is not used so original df ave E as columm


DEL  FED  SML
A   30   59  105
B   25   73   59
C   32   66  108
D   77   54  129

In [131]:
df

DEL  FED  SML
A   30   59  105
B   25   73   59
C   32   66  108
D   77   54  129
E   40   61   69

##### Accessing ROWS

###### 1) using .loc method 

In [135]:
#'''IT is for indexing slicing'''

In [132]:
df.loc['A']#REturns a series object; ALl ROws are also series object


DEL     30
FED     59
SML    105
Name: A, dtype: int32

###### 2) using .iloc method

In [136]:
#'''This is for intiger location'''

In [137]:
df.iloc[0]#it works on number

DEL     30
FED     59
SML    105
Name: A, dtype: int32

In [141]:
#more than one rows and column
df.loc[['A','B'],['SML','FED']]

SML  FED
A  105   59
B   59   73

In [142]:
df.iloc[0:2,0:2]

DEL  FED
A   30   59
B   25   73

In [143]:
df

DEL  FED  SML
A   30   59  105
B   25   73   59
C   32   66  108
D   77   54  129
E   40   61   69

###### conditional selection

In [144]:
newdf = df>50
newdf

DEL   FED   SML
A  False  True  True
B  False  True  True
C  False  True  True
D   True  True  True
E  False  True  True

In [146]:
df[newdf]#it returns NAN n place of False and float in place oe True

DEL  FED  SML
A   NaN   59  105
B   NaN   73   59
C   NaN   66  108
D  77.0   54  129
E   NaN   61   69

###### multiple condition selection

In [147]:
df[(df['DEL']<65) & (df['FED']<40)]

Empty DataFrame
Columns: [DEL, FED, SML]
Index: []

In [148]:
df[(df['DEL']<65) | (df['FED']<40)]

DEL  FED  SML
A   30   59  105
B   25   73   59
C   32   66  108
E   40   61   69

### 1.3 Resetting INDEX

In [150]:
df.reset_index()

index  DEL  FED  SML
0     A   30   59  105
1     B   25   73   59
2     C   32   66  108
3     D   77   54  129
4     E   40   61   69

#### setting an index

In [151]:
names = ['Alpha','Beta','Gamma','Delta','Epsilon']
df['Newcol'] = names
df

DEL  FED  SML   Newcol
A   30   59  105    Alpha
B   25   73   59     Beta
C   32   66  108    Gamma
D   77   54  129    Delta
E   40   61   69  Epsilon

In [152]:
df.set_index('Newcol')

DEL  FED  SML
Newcol                
Alpha     30   59  105
Beta      25   73   59
Gamma     32   66  108
Delta     77   54  129
Epsilon   40   61   69

#### Treatment of Missing Values 

In [155]:
df = pd.DataFrame({'A':[1,2,np.nan,4,7],
                   'B':[np.nan,2,4,6.7,5],
                   'C':[3,np.nan,8,6,8,],
                   'D':[4,np.nan,np.nan,np.nan,9],
                   'E':[9,8,7,6,5]})
df

A    B    C    D  E
0  1.0  NaN  3.0  4.0  9
1  2.0  2.0  NaN  NaN  8
2  NaN  4.0  8.0  NaN  7
3  4.0  6.7  6.0  NaN  6
4  7.0  5.0  8.0  9.0  5

###### 1 - Dropna method

In [157]:
df.dropna()#it drops rows with one or more missing values

A    B    C    D  E
4  7.0  5.0  8.0  9.0  5

In [158]:
df.dropna(axis=1)#  it will drop columns with one or more null values

E
0  9
1  8
2  7
3  6
4  5

In [159]:
df.dropna(thresh=4) #out of the 5 colimns, 
#itshould have values in atleast 4 of them for it to be retain

A    B    C    D  E
0  1.0  NaN  3.0  4.0  9
3  4.0  6.7  6.0  NaN  6
4  7.0  5.0  8.0  9.0  5

###### 2 - FILLNA Method

In [161]:
df.fillna(value='My value')

A         B         C         D  E
0         1  My value         3         4  9
1         2         2  My value  My value  8
2  My value         4         8  My value  7
3         4       6.7         6  My value  6
4         7         5         8         9  5

In [163]:
df.fillna(value=4444)

A       B       C       D  E
0     1.0  4444.0     3.0     4.0  9
1     2.0     2.0  4444.0  4444.0  8
2  4444.0     4.0     8.0  4444.0  7
3     4.0     6.7     6.0  4444.0  6
4     7.0     5.0     8.0     9.0  5

###### Fillna using central values

In [164]:
df['A']

0    1.0
1    2.0
2    NaN
3    4.0
4    7.0
Name: A, dtype: float64

In [165]:
df['A'].fillna(value=df['A'].mean())#filling df['A'] with the mean of A

0    1.0
1    2.0
2    3.5
3    4.0
4    7.0
Name: A, dtype: float64

In [166]:
df['A'].fillna(value=df['A'].median())#filling df['A'] with the median of A

0    1.0
1    2.0
2    3.0
3    4.0
4    7.0
Name: A, dtype: float64

###### Fillna using for loop

In [167]:
df.columns #it pullouts the column names

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [169]:
#for replacing the nan values with mean of the columns for all columns in a datframe
# df['A'].fillna(value=df['A'].mean)
for x in df.columns:
    df[x]=df[x].fillna(value=df[x].mean())
    #df[x] = df[x].fillna(value=df.mean()) #entire Dataframe

In [170]:
df

A      B     C    D  E
0  1.0  4.425  3.00  4.0  9
1  2.0  2.000  6.25  6.5  8
2  3.5  4.000  8.00  6.5  7
3  4.0  6.700  6.00  6.5  6
4  7.0  5.000  8.00  9.0  5

#### Group BY Method

In [2]:
import pandas as pd

In [7]:
groupdata  ={'Company':['Flipkart','Amazon','Flipkart','Myntra','Amazon','Amazon','Jabong','Myntra'],
            'Employee':['vishrut','shreyash','ankit','yash','vikram','anand','raghav','pranav'],
            'Revenue':[400,500,600,200,120,340,500,400]}
df = pd.DataFrame(groupdata)
df

Company  Employee  Revenue
0  Flipkart   vishrut      400
1    Amazon  shreyash      500
2  Flipkart     ankit      600
3    Myntra      yash      200
4    Amazon    vikram      120
5    Amazon     anand      340
6    Jabong    raghav      500
7    Myntra    pranav      400

In [8]:
df.groupby('Company').sum()

Revenue
Company          
Amazon        960
Flipkart     1000
Jabong        500
Myntra        600

In [9]:
df.groupby('Company').mean()

Revenue
Company          
Amazon        320
Flipkart      500
Jabong        500
Myntra        300

In [10]:
df.groupby('Company').count()

Employee  Revenue
Company                    
Amazon           3        3
Flipkart         2        2
Jabong           1        1
Myntra           2        2

In [11]:
df.groupby('Company').mean().loc['Flipkart']

Revenue    500
Name: Flipkart, dtype: int64

In [12]:
df.groupby('Company').describe()

Revenue                                                      
           count   mean         std    min    25%    50%    75%    max
Company                                                               
Amazon       3.0  320.0  190.787840  120.0  230.0  340.0  420.0  500.0
Flipkart     2.0  500.0  141.421356  400.0  450.0  500.0  550.0  600.0
Jabong       1.0  500.0         NaN  500.0  500.0  500.0  500.0  500.0
Myntra       2.0  300.0  141.421356  200.0  250.0  300.0  350.0  400.0

In [13]:
df.groupby('Company').describe().transpose()

Company           Amazon    Flipkart  Jabong      Myntra
Revenue count    3.00000    2.000000     1.0    2.000000
        mean   320.00000  500.000000   500.0  300.000000
        std    190.78784  141.421356     NaN  141.421356
        min    120.00000  400.000000   500.0  200.000000
        25%    230.00000  450.000000   500.0  250.000000
        50%    340.00000  500.000000   500.0  300.000000
        75%    420.00000  550.000000   500.0  350.000000
        max    500.00000  600.000000   500.0  400.000000

#### COmbining Dataframes 

In [16]:
df1 = pd.DataFrame({'Name_OF-Studentds':['vishrut','shreyash','ankit','yash','vikram','anand','raghav','pranav'],
                   'Class':[4,6,7,3,8,5,9,1]})
df2 = pd.DataFrame({'City':['Indore','Nagpur','Roulkella','Jabalpur','Pune','Yevatmal','Jaipur','Indore'],
                   'Age':[20,20,19,19,18,20,19,20]})
df3 = pd.DataFrame({'Roll_No':[54,33,4,55,23,12,53,2],
                   'PinCode':['452001','2321432','125437','234987','657493','876432','987123','435231']})


In [17]:
df1

Name_OF-Studentds  Class
0           vishrut      4
1          shreyash      6
2             ankit      7
3              yash      3
4            vikram      8
5             anand      5
6            raghav      9
7            pranav      1

In [18]:
df2

City  Age
0     Indore   20
1     Nagpur   20
2  Roulkella   19
3   Jabalpur   19
4       Pune   18
5   Yevatmal   20
6     Jaipur   19
7     Indore   20

In [19]:
df3

Roll_No  PinCode
0       54   452001
1       33  2321432
2        4   125437
3       55   234987
4       23   657493
5       12   876432
6       53   987123
7        2   435231

#####  1) cocatination

In [20]:
pd.concat([df1,df2],axis=1) #concatination at the columns

Name_OF-Studentds  Class       City  Age
0           vishrut      4     Indore   20
1          shreyash      6     Nagpur   20
2             ankit      7  Roulkella   19
3              yash      3   Jabalpur   19
4            vikram      8       Pune   18
5             anand      5   Yevatmal   20
6            raghav      9     Jaipur   19
7            pranav      1     Indore   20

In [21]:
pd.concat([df1,df2],axis=0)#conatination at rows

Name_OF-Studentds  Class       City   Age
0           vishrut    4.0        NaN   NaN
1          shreyash    6.0        NaN   NaN
2             ankit    7.0        NaN   NaN
3              yash    3.0        NaN   NaN
4            vikram    8.0        NaN   NaN
5             anand    5.0        NaN   NaN
6            raghav    9.0        NaN   NaN
7            pranav    1.0        NaN   NaN
0               NaN    NaN     Indore  20.0
1               NaN    NaN     Nagpur  20.0
2               NaN    NaN  Roulkella  19.0
3               NaN    NaN   Jabalpur  19.0
4               NaN    NaN       Pune  18.0
5               NaN    NaN   Yevatmal  20.0
6               NaN    NaN     Jaipur  19.0
7               NaN    NaN     Indore  20.0

In [22]:
pd.concat([df1,df2,df3],axis=1)

Name_OF-Studentds  Class       City  Age  Roll_No  PinCode
0           vishrut      4     Indore   20       54   452001
1          shreyash      6     Nagpur   20       33  2321432
2             ankit      7  Roulkella   19        4   125437
3              yash      3   Jabalpur   19       55   234987
4            vikram      8       Pune   18       23   657493
5             anand      5   Yevatmal   20       12   876432
6            raghav      9     Jaipur   19       53   987123
7            pranav      1     Indore   20        2   435231

##### 2) Merging

In [23]:
#pd.merge(df1,df2,how='inner',on='name')'''inner=which is common b/w two dataframe''''''
#pd.merge(df1,df2,how='left',on='name')'''left=everything form left table and common values from right throws NAN value when not match'''
#pd.merge(df1,df2,how='right',on='name')''right=everything form right table and common values from left throws NAN value when not match'''
#pd.merge(df1,df2,how='outer',on='name')''outer=just pull everything'''